config/routes.rb
Rails.application.routes.draw do

  resources :movies
  root :to => redirect('/movies')
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: :get
  match '/login',  to: 'sessions#new', via: :get
  match '/logout', to: 'sessions#destroy', via: :delete

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.all_ratings
    %w(G PG PG-13 NC-17 R)
  end    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save {|user| user.email=user.email.downcase}
  before_save :create_session_token
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
private
  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :set_current_user
  
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @movies = Movie.all
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :set_current_user

  def new
    
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      #sign in and redirect to show page
      cookies.permanent[:session_token]= user.session_token
      redirect_to movies_path
    else
      flash.now[:warning] = 'Invalid email/password combination'
      render 'new'
    end  
  end

  def destroy
    cookies.delete(:session_token) 
    @current_user=nil
    flash[:notice]= 'You have logged out'
    redirect_to movies_path
  end

end  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_current_user, :only=> ['show', 'edit', 'update', 'delete']
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def show
    @user = User.find(params[:id])
 #   @user = @current_user
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Sign up successful! Welcome to Rotten Potatoes"
      redirect_to login_path
    else
      render 'new'
    end  
  end  
  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - if @current_user
        %p You are logged in as #{@current_user.email} (User name: #{@current_user.name})
        = button_to 'Log Out', logout_path, :method => 'delete'
        %p.profile= link_to 'View Profile', user_path(@current_user) 
      = yield

app/views/movies/_movie.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit Movie', edit_movie_path(@movie)
= link_to 'Back to Movie List',  movies_path

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr{:class => ('adult' unless movie.rating =~ /^G|PG$/)}
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

=render :partial => 'movie'

app/views/users/new.html.haml
%p.login= link_to 'Log-in to Rotten Potatoes', login_path

%h1 Sign-up 

-unless @user ==nil
  -if @user.errors.any?
    %ul
    -@user.errors.full_messages.each do |msg|
      %li #{msg}

= form_tag users_path, :id=>'signup_form', :method=> 'post' do

  = label :user, :name, 'Name'
  = text_field :user, 'name'

  = label :user, :email, 'Email'
  = text_field :user, 'email'

  = label :user, :password, 'Password'
  = password_field :user, 'password'

  = label :user, :password_confirmation, 'Confirm Password'
  = password_field :user, 'password_confirmation'

  = submit_tag 'Create my account'

app/views/users/show.html.haml
-# in app/views/users/show.html.haml

%h2 Profile for #{@user.name}

%ul#details
  %li
    name:
    = @user.name
  %li
    e-mail:
    = @user.email

= link_to 'Back to movie list', movies_path